DELETE FROM ratings;
DELETE FROM episode_list;
DELETE FROM episode_judges;
DELETE FROM episodes;
DELETE FROM Cooks_in_Recipe;
DELETE FROM Recipe;
DELETE FROM Cooks;
DELETE FROM Users;

LOAD DATA INFILE 'dummy_recipes.tsv'
INTO TABLE Recipe
FIELDS TERMINATED BY '	'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

SELECT * FROM Recipe;

LOAD DATA INFILE 'dummy_users.tsv'
INTO TABLE Users
FIELDS TERMINATED BY '	'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

SELECT * FROM Users;

#DELETE FROM Cooks;

LOAD DATA INFILE 'dummy_cooks.tsv'
INTO TABLE Cooks
FIELDS TERMINATED BY '	'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

SELECT * FROM Cooks;

#DELETE FROM Cooks_in_Recipe;

LOAD DATA INFILE 'dummy_cooks_in_recipes.tsv'
INTO TABLE cooks_in_recipe
FIELDS TERMINATED BY '	'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

SELECT * FROM cooks_in_recipe;

LOAD DATA INFILE 'dummy_episodes.tsv'
INTO TABLE episodes
FIELDS TERMINATED BY '	'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

SELECT * FROM episodes;

LOAD DATA INFILE 'dummy_ratings.tsv'
INTO TABLE ratings
FIELDS TERMINATED BY '	'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

SELECT * FROM ratings;

LOAD DATA INFILE 'dummy_episode_judges.tsv'
INTO TABLE episode_judges
FIELDS TERMINATED BY '	'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

SELECT * FROM episode_judges;

LOAD DATA INFILE 'dummy_episode_list.tsv'
INTO TABLE episode_list
FIELDS TERMINATED BY '	'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

SELECT * FROM episode_list;